import {
  User1,
  User2,
  User3,
  User4,
  User5,
  User6,
  User7,
} from "../assets/images/pngs";

export const ROWS = [
  {
    id: 1,
    image: User1,
    name: "Savannah Nguyen",
    email: "Savannah Nguyen@gmail.com",
    department: "Marketing",
    contact: "(307) 555-0133",
    age: "23",
    joiningDate: "1/15/12",
  },
  {
    id: 2,
    image: User2,
    name: "Cameron Williamson",
    email: "Cameron Williamson @gmail.com",
    department: "Human Resources",
    contact: "(629) 555-0129",
    age: "23",
    joiningDate: "9/23/16",
  },
  {
    id: 3,
    image: User3,
    name: "Robert Fox",
    email: "Robert Fox@gmail.com",
    department: "Software Engineering",
    contact: "(208) 555-0112",
    age: "23",
    joiningDate: "11/7/16",
  },
  {
    id: 4,
    image: User4,
    name: "Jenny Wilson",
    email: "Jenny Wilson@gmail.com",
    department: "Business Development",
    contact: "(205) 555-0100",
    age: "23",
    joiningDate: "2/11/12",
  },
  {
    id: 5,
    image: User5,
    name: "Floyd Miles",
    email: "Floyd Miles@gmail.com",
    department: "DevOps",
    contact: "(225) 555-0118",
    age: "23",
    joiningDate: "6/21/19",
  },
  {
    id: 6,
    image: User6,
    name: "Kathryn Murphy",
    email: "Kathryn Murphy@gmail.com",
    department: "Sales",
    contact: "(252) 555-0126",
    age: "23",
    joiningDate: "8/30/14",
  },
  {
    id: 7,
    image: User7,
    name: "Guy Hawkins",
    email: "Guy Hawkins@gmail.com",
    department: "UX & UI",
    contact: "(319) 555-0115",
    age: "23",
    joiningDate: "4/21/12",
  },
];
